name: auto merge

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  merge:
    name: auto merge all approved PRs
    runs-on: ubuntu-latest
    steps:
    - name: Check out branch
      uses: actions/checkout@v2
    - name: Run merge script
      uses: ./.github/actions/auto-merge-pr
      id: merge-pr
      with:
        dingtalk-access-token: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
        dingtalk-secret: ${{ secrets.DINGTALK_SECRET }}
        maintainer-team-name: ${{ secrets.MAINTAINER_TEAM_NAME }}
        gh-token: ${{ secrets.GH_TOKEN }}
        ci-command: 'bash ./build.sh'
    - name: Print result
      run: |
        cat /home/runner/work/_temp/*.sh
        echo ${{ steps.merge-pr.outputs.merge-info }}
        echo ${{ steps.merge-pr.outputs.error-log }}
        echo ${{ steps.merge-pr.outputs.pass-log }}
        echo ${{ steps.merge-pr.outputs.merged }}
